name: OmbuLabs Blog
description: The Lean Software Boutique
meta_description: "OmbuLabs Blog, The Lean Software Boutique's blog"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /blog
domain_name: 'http://www.ombulabs.com'
permalink: none
category_dir: 'tags'
excerpt_separator: "<!--more-->"
author_title_prefix: "Articles by "

# Details for the RSS feed generator
url:            'http://www.ombulabs.com/blog'
author:         'OmbuLabs'

exclude: [vendor]
gems: [jekyll-paginate]

authors:
  etagwerker:
    display_name: Ernesto Tagwerker
    gravatar: 9299203e7e9b9ae35e39eb66f3155f15
    email: ernesto@ombulabs.com
    twitter: etagwerker
    github: etagwerker
  mauro-oto:
    display_name: Mauro Otonelli
    gravatar: 350875eb8fce8553e12040c5a1f5d5d0
    email: mauro@ombulabs.com
    twitter: mauro_oto
    github: mauro-oto
  schmierkov:
    display_name: Sirko Sittig
    gravatar: ff0ffbb39659d36ad6aabcd0b4715c1b
    email: sirko@ombulabs.com
    twitter: schmierkov
    github: schmierkov
